language: node_js
install:
  - sudo npm install html-minifier -g

script:
  - html-minifier --minify-css 1 --minify-js 1 --html5 --input-dir . --output-dir minify --file-ext html --collapse-whitespace --collapse-inline-tag-whitespace --remove-comments

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
