language: node_js
install:
  - sudo npm install html-minifier -g

script:
  - 
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
